name: Data Ingestion Pipeline
on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  workflow_dispatch:      # Allow manual runs

jobs:
  ingest-market-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Data Ingestion Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python data_ingestion.py
